// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFhIs0m9eURiE-vCDGch6YrkpC8s3XuE',
    appId: '1:396011930229:web:0a40710d6d362758d96e3c',
    messagingSenderId: '396011930229',
    projectId: 'e-farm-3b67d',
    authDomain: 'e-farm-3b67d.firebaseapp.com',
    storageBucket: 'e-farm-3b67d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3qaqB4PIRUJUAAs4luzdR3llwFt2U_6g',
    appId: '1:396011930229:android:5cc61cdabd7d4d73d96e3c',
    messagingSenderId: '396011930229',
    projectId: 'e-farm-3b67d',
    storageBucket: 'e-farm-3b67d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6K990rtYBDdZi-5xKPYA89zYIclNW3s',
    appId: '1:396011930229:ios:0546aec7fe61f762d96e3c',
    messagingSenderId: '396011930229',
    projectId: 'e-farm-3b67d',
    storageBucket: 'e-farm-3b67d.appspot.com',
    iosBundleId: 'com.efarm.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6K990rtYBDdZi-5xKPYA89zYIclNW3s',
    appId: '1:396011930229:ios:4e98f861fca720a4d96e3c',
    messagingSenderId: '396011930229',
    projectId: 'e-farm-3b67d',
    storageBucket: 'e-farm-3b67d.appspot.com',
    iosBundleId: 'e-fa',
  );
}
